config/routes.rb
Rails.application.routes.draw do

  get 'fmc/index'
  get 'status/index'

  get 'galaxies/remove_star'
  post 'galaxies/update_star'
  resources :galaxies , only: [:index, :show]

  match "/" => "positions#index", via: [:get, :post]
  get 'positions/:id', to: "positions#show"
  post 'positions/find_by_alg'

  get 'alg_sets/update_cookie/', to: "alg_sets#update_cookie"
  resources :alg_sets
  get 'alg_sets/compute/:ids', to: "alg_sets#compute"
  get 'alg_sets/:id/algs', to: "alg_sets#algs", as: "mirrored_list"

  get 'hemlig', to: 'status#index'
  get 'fmc', to: 'fmc#index'

  get "wca_callback" => "oauth#wca"
  get "wca_logout" => "oauth#wca_logout"
  get "fake_wca_login" => "oauth#fake_wca_login"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '*path', to: 'errors#not_found', via: :all

end

app/models/alg_set.rb
# frozen_string_literal: true

class AlgSet < ApplicationRecord
  ARE_WE_ADMIN = Rails.env.development?

  belongs_to :wca_user, optional: true

  validates :name, presence: true
  validates_inclusion_of :subset, :in => %w(all eo)

  validate do
    algs.split(' ').each do |mirror_alg_name|
      ma = MirrorAlgs.combined(mirror_alg_name)

      errors.add(:algs, "'#{mirror_alg_name}' is not a valid mirrored alg pair") unless ma
      errors.add(:algs, "'Nothing' is not a real alg") if ma&.ids == [RawAlg::NOTHING_ID]
    end
  end

  before_validation do
    self.algs ||= ''
    self.algs = self.algs.split(' ').uniq.sort.join(' ') # sort names
  end


  attr_accessor :editable_by_this_user # Set by controller

  def self.make(algs: nil, name: '--', subset: 'all')
    algs = algs.join(' ') if algs.respond_to? :join
    AlgSet.create!(subset: subset, name: name, algs: algs, wca_user_id: nil)
  end

  before_save do
    fact.save!
  end

  def self.for_user(wca_user_id)
    AlgSet.where("predefined=true OR wca_user_id=#{wca_user_id || '-99'}")
  end

  def fact
    @fact ||= AlgSetFact.find_or_create_by!(algs_code: set_code).tap do |fact|
      fact.alg_set = self
      self.alg_set_fact_id = fact.id
    end
  end

  def replace_algs(new_algs)
    self.algs = new_algs
    self.alg_set_fact_id = nil
    @fact = nil
    self
  end

  def set_code
    (algs+' ').gsub(/\.\D[0-9\-]* /, '').strip + subset.first
  end

  def data_only
    fact.data_only
    self
  end

  def pos_subset
    case subset
      when 'all' then Position.real
      when 'eo'  then Position.real.where(eo: '4')
      else raise "Invalid subset '#{subset}'"
    end
  end

  @@pos_ids = {} # cache position ids per subset (all/eo)
  def subset_pos_ids
    @@pos_ids[subset] ||= pos_subset.pluck(:id)
  end

  def applies_to(position)
    position.eo == '4' || subset == 'all'
  end

  def include?(combo_alg)
    ids.include?(combo_alg.alg1_id) && ids.include?(combo_alg.alg2_id)
  end

  def has_facts
    fact.fully_computed?
  end

  def ids
    @ids ||= ('Nothing.-- ' + algs).split(' ').map { |ma_name| MirrorAlgs.combined(ma_name).ids }.flatten.sort.freeze
  end

  def mirror_algs
    algs.split(' ').map { |ma_name| MirrorAlgs.combined(ma_name) }
  end

  def full_coverage?
    return nil unless fact.coverage
    fact.coverage == subset_pos_ids.count
  end

  def uncovered_ids
    fact.uncovered_ids
  end

  def uncovered_ids_arr
    fact.uncovered_ids.split(' ')
  end

  def average(by_measure)
    case by_measure.to_sym
      when :speed  then fact.average_speed
      when :length then fact.average_length
      else raise "Unknown measure '#{by_measure}'"
    end
  end

  def dropdown_name
    dash = predefined ? '-' : '·'
    subset + dash + name
  end

  # This is to move AlgSets between dev and prod
  def to_yaml
    excluded_columns = %w(id created_at updated_at wca_user_id alg_set_fact_id)
    values = attributes.delete_if { |key, value| excluded_columns.include?(key) }

    # AlgSets made here are either predefined or owned by Lars.
    unless values['predefined']
      values['wca_user_id'] = WcaUser.find_by!(wca_id: '1982PETR01').id
    end

    YAML.dump(values)
  end

  def self.from_yaml(yaml_string)
    create!(YAML.load(yaml_string))
  end

  def to_s
    "AlgSet #{id}: '#{name}' (#{subset})"
  end

  # -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+- -+=+-

  def self.menu_options(login)
    sets = AlgSet.for_user(login&.db_id).to_a
    sets.sort_by {|as| [as.predefined ? 0 : 1, as.subset, as.algs.length] }.map{|as| [as.dropdown_name, as.id] }
  end

  SMALL_39 = %w(F1.F3 F2.F4 G1.G6 G2.G7 G3.G9 G4.G8 G5.G10 H12.H31 H15.H33 H16.H35 H5.H29 I19.I70 I3.I63 I54.I114 J101.J423 J103.J401 J112.J409 J126.J368 J132.J371 J16.J325 J179.J487 J183.J483 J199.J495 J204.J502 J211.J517 J212.J519 J219.J528 J266.J538 J275.J550 J34.J39 J629.J652 J637.J657 J639.J658 J78.J387 J82.J390 J93.J417 J95.J416 J98.J419 J99.J421)
  QUICK_49 = %w(F2.F4 G2.G7 G3.G9 G4.G8 G5.G10 H15.H33 H16.H35 H17.H36 H19.H38 H6.H30 H9.H23 I19.I70 I21.I67 I3.I63 I49.I105 I58.I115 I59.I116 J103.J401 J110.J411 J112.J409 J126.J368 J131.J370 J140.J382 J16.J325 J183.J483 J199.J495 J204.J502 J212.J519 J216.J521 J219.J528 J246.J455 J266.J538 J34.J39 J49.J54 J629.J652 J637.J657 J82.J390 J93.J417 J95.J416 J97.J420 J99.J421 F1.F3 G1.G6 H8.H22 H13.H34 J98.J419 I55.I110 J301.J571 H14.H32)
  FEW_49 = %w(F2.F4 G1.G6 G2.G7 G3.G9 G4.G8 G5.G10 H1.H25 H11.H21 H12.H31 H14.H32 H15.H33 H16.H35 H5.H29 H8.H22 I19.I70 I22.I72 I3.I63 I30.I90 I54.I114 I59.I116 J101.J423 J103.J401 J112.J409 J119.J372 J126.J368 J146.J431 J16.J325 J179.J487 J183.J483 J199.J495 J204.J502 J212.J519 J266.J538 J34.J39 J629.J652 J637.J657 J638.J659 J639.J658 J77.J385 J93.J417 J95.J416 J98.J419 J99.J421 F1.F3 H3.H28 I55.I110 H2.H27 I58.I115 H6.H30)

  EO_SMALL_14 = %w(G3.G9 G4.G8 G5.G10 J252.J470 J44.J45 I129.I137 J266.J538 I120.I125 J51.J56 I28.I88 J112.J409 J260.J467 I20.I68 J93.J417)
end

app/controllers/alg_sets_controller.rb
# frozen_string_literal: true

class AlgSetsController < ApplicationController
  def index  # === Routed action ===
    setup_leftbar
    @list_classes = "algset-list size-#{@text_size}"
    @all_sets = AlgSet.for_user(@login&.db_id).map(&:data_only).sort_by {|as| [as.predefined ? 0 : 1, as.subset, as.algs.length] }
    @all_sets.each { |as| as.editable_by_this_user = can_change(as) }
    @to_compute = @all_sets.reject(&:has_facts).map(&:id).join(',')
  end

  def new  # === Routed action ===v
    raise "Not allowed to create Algset" unless can_create

    setup_leftbar
    @algset = AlgSet.new
  end

  def algset_params(operation, non_posted_params = {})
    permitted = [:name, :description] + (operation == :create ? [:subset, :algs] : [])
    params.require(:alg_set).permit(permitted).merge(non_posted_params)
  end

  def create  # === Routed action ===
    raise "Not allowed to create Algset" unless can_create

    setup_leftbar

    params[:alg_set][:algs] = params[:alg_set][:algs].split(' ').map{|alg| MirrorAlgs.combined_name_for(alg) || alg}.join(' ') # normalize in model?
    @algset = AlgSet.new(algset_params(:create, @login ? {wca_user_id: @login.db_id} : {predefined: true}))
    if @algset.save
      activate(@algset)
      flash[:success] = "Alg set '#{@algset.name}' created"
      redirect_to alg_sets_path
    else
      render new_alg_set_path
    end
  end

  def destroy  # === Routed action ===
    algset = AlgSet.find(params[:id])
    raise "Not allowed to delete Algset #{algset.id}" unless can_change(algset)

    flash[:success] = "Algset '#{algset.name}' deleted"
    algset.destroy
    redirect_to alg_sets_url
  end

  def show  # === Routed action ===
    redirect_to alg_sets_url unless request.xhr?

    @algset = AlgSet.find(params[:id]).data_only
    @can_edit = can_change(@algset)
  end

  def edit  # === Routed action ===
    setup_leftbar
    @algset = AlgSet.find(params[:id])
    raise "Not allowed to edit Algset #{@algset.id}" unless can_change(@algset)
  end

  def update  # === Routed action ===
    setup_leftbar
    @algset = AlgSet.find(params[:id]).data_only
    raise "Not allowed to update Algset #{@algset.id}" unless can_change(@algset)

    algs_change = alter_algs(@algset, params[:add_algs], params[:remove_algs])
    if algs_change[:replacement_algs]
      @algset.replace_algs(algs_change[:replacement_algs])
    end

    if @algset.errors.empty? && @algset.update_attributes(algset_params(:update))
      activate(@algset)
      flash[:success] = algs_change[:summary] || "Algset '#{@algset.name}' updated"
      redirect_to alg_sets_path
    else
      render 'edit'
    end
  end

  # Figure out the new alg set from the preexisting set and the user entered add/removals. Set algset.errors if the input is bad.
  def alter_algs(algset, adds, removes)
    return {} if adds.blank? && removes.blank?

    old_malgs = algset.algs.split(' ')
    add_malgs = adds.upcase.split(' ')
    remove_malgs = removes.upcase.split(' ')
    errors = []

    (add_malgs + remove_malgs).each do |user_ma|
      errors << "'#{user_ma}' is not combinable (yet)" unless MirrorAlgs.combined_name_for(user_ma)
    end

    add_malgs = add_malgs.map{|ma| MirrorAlgs.combined_name_for(ma)}
    remove_malgs = remove_malgs.map{|ma| MirrorAlgs.combined_name_for(ma)}

    remove_malgs.each do |user_ma|
      errors << "'#{user_ma}' is not in this algset" unless old_malgs.include?(user_ma) || user_ma.blank?
    end

    if errors.empty?
      summary = (add_malgs.present? ? "Added "+add_malgs.join(', ') : "") + (remove_malgs.present? ? " Removed "+remove_malgs.join(', ') : "")
      { replacement_algs: (old_malgs + add_malgs - remove_malgs).sort.join(' '), summary: summary }
    else
      errors.each { |error| algset.errors.add(:base, error)}
      { errors: algset.errors.full_messages}
    end
  end

  def algs  # === Routed action ===
    setup_leftbar
    @algset = AlgSet.find(params[:id])
    @mirror_algs = @algset.mirror_algs.sort_by{|ma| ma.algs[0].position.cop }
    @list_classes = "bflist mirroralg-list size-#{@text_size}-wc"
    @columns = Column.named([:name_link, :cop, :eop, :alg, :show])
    use_svgs
  end

  def update_cookie  # === Routed action ===
    Fields.update_list_format(cookies, params.permit!.to_h.symbolize_keys)
    render json: { fresh_cookie: cookies[Fields::COOKIE_NAME] }
  end


  def can_create
    @login || AlgSet::ARE_WE_ADMIN
  end

  def can_change(algset)
    is_owned_by_user = @login&.db_id && (@login.db_id == algset.wca_user_id)
    is_owned_by_user || AlgSet::ARE_WE_ADMIN
  end

  def compute  # === Routed action ===
    params[:ids].split(',').each { |id| AlgSet.find(id).fact.compute.save! }
    render json: { success: :true }
  rescue  Exception => e
    render json: { error: e.message }
  end

  def activate(alg_set)
    @list_format.combos = 'merge' if @list_format.combos == 'none'
    @list_format.algset = alg_set.id

    Fields.store_list_format(cookies, @list_format.to_h)
  end

end

app/helpers/alg_sets_helper.rb
# frozen_string_literal: true

module AlgSetsHelper
  def avg_format(avg)
    return '--' unless avg
    '%.3f' % avg
  end

  def fmt_coverage_percent(algset)
    return spinner unless algset.fact.coverage
    "#{100 * algset.fact.coverage/algset.subset_pos_ids.count}%"
  end

  def fmt_uncovered(algset)
    return AlgSetFact::TOO_MANY_UNCOVERED if algset.uncovered_ids == AlgSetFact::TOO_MANY_UNCOVERED

    to_show = 16
    and_more = algset.uncovered_ids_arr.count > to_show ? " + #{algset.uncovered_ids_arr.count - to_show} more" : ""
    algset.uncovered_ids_arr.first(to_show).map{|pos_id| link_to Position.find(pos_id).display_name, "positions/#{pos_id}" }.join(' ').html_safe + and_more
  end

  def fmt_coverage_fraction(algset, parens = false)
    return '' if !algset.fact.coverage || algset.full_coverage?
    parens_if("#{algset.fact.coverage}/#{algset.subset_pos_ids.count}", parens)
  end

  def fmt_avg_length(algset)
    return spinner unless algset.fact.average_length
    parens_if('%.3f' % (algset.fact.average_length || 0), ! algset.full_coverage?)
  end

  def fmt_avg_speed(algset)
    return spinner unless algset.fact.average_speed
    parens_if('%.3f' % (algset.fact.average_speed || 0), ! algset.full_coverage?)
  end

  def subset_options
    ['', ['All Positions (3916)', 'all'], ['Oriented Edges (494)', 'eo']]
  end

  def subset_long_name(algset)
    @@long_names ||= {}.tap{|h| subset_options.each { |so| h[so.last] = so.first } }
    @@long_names[algset.subset]
  end

  def fmt_algs(algset_algs)
    return '(no algs)' if algset_algs.empty?

    algset_algs
        .sub("G", "|G").sub("H", "|H").sub("I", "|I").sub("J", "|J").sub("K", "|K").sub("L", "|L").sub("M", "|M").sub("N", "|N").sub("O", "|O").split('|')
        .select{|x| x.present?}
        .join('●● ')
  end

  def owner(algset)
    algset.predefined ? 'system' : algset.wca_user&.full_name
  end

  def parens_if(value, yes)
    p1, p2 = (yes ? ['(', ')'] : ['', ''])
    p1 + value + p2
  end

  def spinner
    content_tag(:span, '--', class: 'spintext')
  end
end

app/views/alg_sets/_mirror_fragment.html.haml
.combinables
  Combo ready algs are marked by
  %span.combo-ready c
  in the tables. More can be added!
  %p Currently all up to 10 moves (F,G,H,J), plus these #{MirrorAlgs.k_plus_names.count} mirror pairs.
  .mirrored-algs
    =fmt_algs(MirrorAlgs.k_plus_names.join(' '))

:javascript
    $("#{fields}").keyup(function(event) {
      $(this).val( $(this).val().toUpperCase().replace(/[^A-Z\d .']/g, '') );
  });

app/views/alg_sets/_show.html.haml
%table.show_table
  %tr
  %tr
    %td Name
    %td
      =@algset.name
  %tr
    %td Description
    %td
      =@algset.description
  %tr
    %td Subset
    %td
      =subset_long_name(@algset)
  %tr
    %td Algs
    %td
      .mirrored-algs
        =fmt_algs(@algset.algs)
  %tr
    %td Coverage
    %td
      = fmt_coverage_percent(@algset) + ' ' + fmt_coverage_fraction(@algset, :parens)
  -unless @algset.full_coverage?
    %tr
      %td Uncovered
      %td.uncovered
        = fmt_uncovered(@algset)
  %tr
    %td Owner
    %td
      = owner(@algset)
  - if @can_edit
    %tr
      %td
      %td
        =link_to('Edit', edit_alg_set_path(@algset), class: 'knapp knapp-enabled knapp16')

app/views/alg_sets/algs.html.haml
= render 'leftbar', section: Section::ALGSETS

= render 'page_rotation'

.algs-header
  %h4 #{@algset.dropdown_name} Algs
  .ok-button
    =link_to('OK', alg_sets_path, class: 'knapp knapp-enabled')

%table{class: @list_classes}
  %tr
    %th{colspan: @columns.size}
      Alg
    %th{colspan: @columns.size}
      Mirror Alg
  -@mirror_algs.each do |ma|
    %tr
      -presenter = RawAlgColumns.new(ma.algs[0])
      -@columns.each do |column|
        =list_td(presenter, column)
      -presenter = RawAlgColumns.new(ma.algs[1])
      -@columns.each do |column|
        =list_td(presenter, column)

app/views/alg_sets/edit.html.haml
= render 'leftbar', section: Section::ALGSETS

.alg-set-form
  %h3 Edit AlgSet

  - if @algset.errors.any?
    #error_explanation
      %ul
      - @algset.errors.full_messages.each do |msg|
        %li
          = msg
  =form_for(@algset, html: {class: "edit_algset"}) do |f|
    %p
      = f.label :name
    %p
      = f.text_field :name, class: 'form-control'

    %p
      = f.label :subset
    %p{style: 'font-size: 12px; margin: 0 0 0 20px;'}
      = subset_long_name(@algset)

    %p
      = f.label :description
    %p
      = f.text_area :description, size: "50x3", class: 'form-control'

    %p
      = f.label :algs
    %p{style: 'margin: 0;'}
      .mirrored-algs
        =fmt_algs(@algset.algs)
    %p
      = f.label 'Add algs'
      = text_field_tag :add_algs, params[:add_algs]
      = f.label 'Remove algs'
      = text_field_tag :remove_algs, params[:remove_algs]

    %p
      = f.submit "Save changes", class: "knapp knapp-enabled knapp16", style: "font-weight: 700;"
      = link_to "Cancel", alg_sets_path, class: "knapp knapp-enabled knapp16", style: "font-weight: 700;"

=render('mirror_fragment', fields: '#add_algs,#remove_algs')

app/views/alg_sets/index.html.haml
= render 'leftbar', section: Section::ALGSETS

.index-header
  %h2 Combo Alg Sets
  - if @login
    =link_to('Create', new_alg_set_path, class: 'knapp knapp-enabled knapp16')
  - else
    %div{style: 'font-size: 9px;'} (log in to create)
%p

%table{class: @list_classes}
  %tr
    %th name
    %th algs
    %th avg length
    %th avg speed
    %th coverage
    %th owner
    %th
    %th
    %th
    %th
  - @all_sets.each do |algset|
    %tr
      %td
        =algset.dropdown_name
      %td
        =algset.algs.split(' ').count
      %td
        =fmt_avg_length(algset)
      %td
        =fmt_avg_speed(algset)
      %td
        =fmt_coverage_percent(algset)
        %span{style: "font-size: 8px;"}
          = fmt_coverage_fraction(algset)
      %td
        =owner(algset)
      %td
        =link_to('Show', alg_set_path(algset), class: 'knapp knapp-enabled', remote: true)
      %td
        =link_to('Algs', mirrored_list_path(algset), class: 'knapp knapp-enabled')
      %td
        - if algset.editable_by_this_user
          =link_to('Edit', edit_alg_set_path(algset), class: 'knapp knapp-enabled')
      %td
        - if algset.editable_by_this_user && (not algset.predefined)
          = link_to "Remove", algset, method: :delete, data: {confirm:"Remove '#{algset.dropdown_name}'?"}, class: 'knapp knapp-enabled'

#show-algset

-if @to_compute.present?
  :javascript
    console.log("Recomputing stats: /alg_sets/compute/#{@to_compute}");
    $.get("/alg_sets/compute/#{@to_compute}", function(data) {
      if (data.success) {
        location.reload();
      } else {
        console.log("/alg_sets/compute/#{@to_compute} failed: ", data.error);
      }
    });

:javascript
  $('#{Fields::JQUERY_SELECTOR}').change(function(event) {
    var id = event.target.id;
    $.get("/alg_sets/update_cookie/?"+id+"="+$("#"+id).val(), function(response) {
      Cookies.set('field_values', response.fresh_cookie, { expires: 3650 });
      window.location.reload(true);
    });
  });

app/views/alg_sets/new.html.haml
= render 'leftbar', section: Section::ALGSETS

.alg-set-form
  %h3 Create AlgSet

  - if @algset.errors.any?
    #error_explanation
      %ul
      - @algset.errors.full_messages.each do |msg|
        %li
          = msg
  =form_for(@algset, html: {class: "edit_algset"}) do |f|
    %p
      = f.label :name
    %p
      = f.text_field :name, class: 'form-control'

    %p
      = f.label :subset
    %p
      = f.select(:subset, subset_options)

    %p
      = f.label :description
    %p
      = f.text_area :description, size: "50x3", class: 'form-control'

    %p
      = f.label :algs
    %div{style: "font-size: 9px;"}
      One alg name (H4 or H26) will be expanded to a mirrored pair (H4.H26). H4' is the reverse H4 (H10). H4.H26 also works. See below for currently combinable algs.
    %p
      = f.text_area :algs, size: "80x4", class: 'form-control'

    %p
      = f.submit "Create", class: "knapp knapp-enabled knapp16", style: "font-weight: 700;"
      = link_to "Cancel", alg_sets_path, class: "knapp knapp-enabled knapp16", style: "font-weight: 700;"

=render('mirror_fragment', fields: '#alg_set_algs')

app/views/alg_sets/show.js.erb
$("#show-algset").html("<%= j render(partial: 'show') %>");
$("#show-algset").dialog({
  modal: true,
  closeOnEscape: true,
  width: 400,
  dialogClass: 'lars-dialog',
});