config/routes.rb
Rails.application.routes.draw do

  get 'fmc/index'
  get 'status/index'

  get 'galaxies/remove_star'
  post 'galaxies/update_star'
  resources :galaxies , only: [:index, :show]

  match "/" => "positions#index", via: [:get, :post]
  get 'positions/:id', to: "positions#show"
  post 'positions/find_by_alg'

  get 'alg_sets/update_cookie/', to: "alg_sets#update_cookie"
  resources :alg_sets
  get 'alg_sets/compute/:ids', to: "alg_sets#compute"
  get 'alg_sets/:id/algs', to: "alg_sets#algs", as: "mirrored_list"

  get 'hemlig', to: 'status#index'
  get 'fmc', to: 'fmc#index'

  get "wca_callback" => "oauth#wca"
  get "wca_logout" => "oauth#wca_logout"
  get "fake_wca_login" => "oauth#fake_wca_login"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '*path', to: 'errors#not_found', via: :all

end

app/models/galaxy.rb
# frozen_string_literal: true

class Galaxy < ApplicationRecord
  belongs_to :wca_user
  has_many :stars

  validates :starred_type, inclusion: { in: %w(raw_alg combo_alg)}

  def self.make(wca_user_id, style, alg_ids, type = 'raw_alg')
    self.create!(wca_user_id: wca_user_id, style: style, starred_type: type).tap do |new_galaxy|
      alg_ids.each { |alg_id| new_galaxy.add(alg_id) }
    end
  end

  def self.star_styles_for(wca_user_id, alg_id, type)
    Galaxy.joins(:stars).where(wca_user_id: wca_user_id, starred_type: type, stars: {starred_id: alg_id}).pluck(:style).sort
  end

  def self.star_styles_by_alg(wca_user_id, alg_ids, type)
    Hash.new { |hash, key| hash[key] = []}.tap do |result|
      pairs = Galaxy.joins(:stars).where(wca_user_id: wca_user_id, starred_type: type, stars: {starred_id: alg_ids}).pluck(:starred_id, :style)
      pairs.sort.each{|pair| result[pair.first] << pair.last }
    end
  end

  def alg_ids
    stars.pluck(:starred_id)
  end

  def alg_names
    stars.map{|star| star.alg.name }.sort
  end

  def toggle(alg_id)
    if include?(alg_id)
      remove(alg_id)
    else
      add(alg_id)
    end
  end

  def add(alg_id)
    stars.create!(starred_id: alg_id)
  end

  def remove(alg_id)
    Star.where(galaxy_id: id, starred_id: alg_id).delete_all
  end

  def include?(id)
    stars.exists?(starred_id: id)
  end

  def css_class
    prefix = (starred_type == 'raw_alg' ? 'star' : 'cstar')
    prefix+style.to_s
  end

  def to_s
    "Galaxy: user: #{wca_user_id} style: #{style} #{starred_type}"
  end
end

app/controllers/galaxies_controller.rb
# frozen_string_literal: true

class GalaxiesController < ApplicationController
  def index
    redirect_to('/') unless @login

    setup_leftbar
    @columns = Column.named([:name_link, :cop, :eop, :alg, :stars, :remove_star])
    @stars = Star.where(galaxies: {wca_user_id: @login&.db_id})
                 .order(['galaxies.starred_type DESC', 'galaxies.style'])
                 .includes(:galaxy)
                 .to_a
    @per_style = @stars.chunk{ |line| line.galaxy }.to_a
    use_svgs
  end

  def show
    setup_leftbar
    @columns = Column.named([:name_link, :cop, :eop, :alg])
    @galaxy = Galaxy.find(params[:id])
    @stars = Star.where(galaxy_id: @galaxy.id).to_a
    use_svgs
  end

  def update_star
    raise "Must be logged in to update stars" unless @login

    alg_type, style = Star.select_from_class(params[:star_class])
    galaxy = Galaxy.find_or_create_by(wca_user_id: @login.db_id, style: style, starred_type: alg_type)
    alg_id = params[:starred_id].to_i
    galaxy.toggle(alg_id)

    render json: Galaxy.star_styles_for(@login.db_id, alg_id, alg_type)
  end


  def remove_star
    raise 'Must be logged in' unless @login

    galaxy = Galaxy.find(params[:galaxy_id])
    raise 'Star removal failed' unless galaxy.wca_user_id == @login.db_id

    death_star = Star.find_by(galaxy_id: galaxy.id, starred_id: params[:starred_id])

    flash[:success] = "Star removed"
    death_star.destroy
    redirect_back(fallback_location: '/')
  end
end

app/views/galaxies/_star_table.html.haml
%table{class: "galaxy-list size-#{@text_size}"}
  %tr
    -@columns.each do |column|
      %th= column.header
  - stars.sort_by{|star| star.alg.position.display_name }.each do |star|
    - alg_presenter = star.alg.presenter(OpenStruct.new(login: @login, star: star))
    %tr
      -@columns.each do |column|
        =list_td(alg_presenter, column)
  -if galaxy.starred_type == 'raw_alg'
    %tfoot
      %tr
        %td{colspan: 99}
          = galaxy.alg_names.join(' ')

app/views/galaxies/index.html.haml
= render 'leftbar', section: Section::FAVORITES

.galaxy-header Your Starred Algs

-unless @per_style.present?
  %div{style: 'text-align: center; margin-top: 30px;'} To add favorites, use the ☆ column in an alg list.

-@per_style.each do |galaxy_and_stars|
  -galaxy = galaxy_and_stars.first

  .big-star{class: galaxy.css_class}
  =render 'star_table', galaxy: galaxy, stars: galaxy_and_stars.last
  .public-link
    =link_to('Public link', galaxy_url(galaxy))

app/views/galaxies/show.html.haml
= render 'leftbar', section: Section::FAVORITES

.galaxy-header
  Algs by
  #{@galaxy.wca_user.full_name}

%div{style: 'height: 20px'}

=render 'star_table', galaxy: @galaxy, stars: @stars