config/routes.rb
Rails.application.routes.draw do

  get 'fmc/index'
  get 'status/index'

  get 'galaxies/remove_star'
  post 'galaxies/update_star'
  resources :galaxies , only: [:index, :show]

  match "/" => "positions#index", via: [:get, :post]
  get 'positions/:id', to: "positions#show"
  post 'positions/find_by_alg'

  get 'alg_sets/update_cookie/', to: "alg_sets#update_cookie"
  resources :alg_sets
  get 'alg_sets/compute/:ids', to: "alg_sets#compute"
  get 'alg_sets/:id/algs', to: "alg_sets#algs", as: "mirrored_list"

  get 'hemlig', to: 'status#index'
  get 'fmc', to: 'fmc#index'

  get "wca_callback" => "oauth#wca"
  get "wca_logout" => "oauth#wca_logout"
  get "fake_wca_login" => "oauth#fake_wca_login"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '*path', to: 'errors#not_found', via: :all

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :handle_wca_login
  around_action :keep_track

  private

  def setup_leftbar
    @text_size = cookies[:size] || 'm'
    @position_set = cookies[:zbll] ?  'eo' : 'all'
    @list_format = Fields.read_list_format(cookies)
    @lb_sections = [Section::ALGS, Section::FAVORITES, Section::ALGSETS, Section::FMC]
    @lb_disabled = @login ? '' : [Section::FAVORITES]
  end

  def use_svgs
    @rendered_svg_ids = Set.new
  end

  @@request_count = Hash.new(0)
  @@user_agent_count = Hash.new(0)
  @@bot_request_count = Hash.new(0)
  @@bot_user_agent_count = Hash.new(0)
  @@trouble_list = []

  def handle_wca_login
    if session[:wca_login]
      if Time.now.to_i > (session[:wca_login]['expires'] || 0)
        flash.now[:notification] = 'WCA login expired'
        session.delete(:wca_login)
      else
        sn = session[:wca_login]
        @login = OpenStruct.new(name: sn['name'], db_id: sn['db_id'], wca_id: sn['wca_id'])
      end
    end
    @dev_marker_class = 'dev-marker' if Rails.env.development?
  end

  BOT_AGENTS = %w(AhrefsBot DotBot Googlebot HostTracker MJ12bot Baiduspider bingbot Slurp YandexBot Sogou BUbiNG linguee Optimizer commoncrawl)
  def keep_track
    user_agent = request.env['HTTP_USER_AGENT']
    action = "#{params[:controller]}::#{params[:action]}"

    known_bot = BOT_AGENTS.any? { |t| user_agent&.include?(t) }
    unless known_bot
      @@request_count[action] += 1
      @@user_agent_count[user_agent] += 1
    else
      @@bot_request_count[action] += 1
      @@bot_user_agent_count[user_agent] += 1
    end


    yield
  rescue Exception => e
    @@trouble_list << "Exception at #{Time.now} --- #{e.message} #{known_bot ? '(BOT)' : ''}"
    raise
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def spaced_number(count)
    number_with_delimiter(count, delimiter: "\u2009") # 2009 is "thin space"
  end

  def alg_sections(alg)
    sections = alg.split(' ').each_slice(4).to_a.map{|slice| slice.join(' ')}
    sections.map.with_index { |slice, i| hlp.content_tag(:span, slice, class: (i.odd? ? :odd : :even)) }
  end

  def list_td(presenter, column)
    if column.is_svg
      svg_params = column.content(presenter)
      content_tag(:td, render('cube_icon', svg_params))
    else
      column.content(presenter)
    end
  end

  def hlp
    ActionController::Base.helpers
  end
end

app/views/application/_find_by_alg.html.haml
=form_tag url_for(controller: 'positions', action: 'find_by_alg'), method: 'post', id: 'find_by_alg', remote: true, enforce_utf8: false do
  Find by Alg:
  =text_field_tag "input_alg", nil, placeholder: 'notation/alg name'
  =text_field_tag "display_alg", nil, placeholder: 'BRDFLU translation', disabled: true
  =hidden_field_tag "post_alg"
  =submit_tag "", style: "display:none;", disabled: true
  #find_by_alg_msg{style: "padding: 10px; display:none;"}

:javascript
  $('#find_by_alg').on('ajax:success', function(e, data, status, xhr) {
    var result = JSON.parse(xhr.responseText);
    if (result.ll_code) {
      var new_url = '/positions/' + result.ll_code + '?prot=' + result.prot;
      new_url += (result.packed_alg ? '&hl_alg=' + result.packed_alg : '');
      new_url += (result.alg_id     ? '&hl_id='  + result.alg_id     : '');

      window.location.href = new_url;
    } else {
      bad_alg_dialog(result.error || "We didn't even get an error...");
    }
  });

  function bad_alg_dialog(message) {
    $('#find_by_alg_msg').text(message);
    $('#find_by_alg_msg').dialog({
      width: '350px', title: 'Find by Alg problem', modal: true, closeOnEscape: true, dialogClass: 'lars-dialog'
    });
  }

  function sync_alg_fields() {
    var display_alg_text = "-";
    try {
      var clean_input = $('#input_alg').val().replace(/[\(\)\t]/g, ''); // filter out tabs and braces
      display_alg_text = /^\D\d+[mM']*$/.test(clean_input) ? clean_input.toUpperCase() : new Alg(clean_input).unhand();
    }
    catch(err) {}
    $('#display_alg').val(display_alg_text);
    $('#post_alg').val(display_alg_text);

    if ($('#input_alg').val().length > 25) {
      $('#find_by_alg').addClass('wide');
    }
    $("#find_by_alg :submit").prop( "disabled", display_alg_text === '-' );
  }

  $('#input_alg').on("blur", function(event) {
    $('#find_by_alg').removeClass('focus');
  });

  $('#input_alg').on("focus", function(event) {
    $('#find_by_alg').addClass('focus');
  });

  $('#input_alg').on("input", function(event) {
    sync_alg_fields();
  });

app/views/application/_leftbar.html.haml
.leftflex
  %nav.section
    %h1
      %span
        section
    .middiv
      %span.list-size
        = select_tag(:sectionator, options_for_select(@lb_sections, selected: section, disabled: @lb_disabled), class: 'list-size__select')
    -unless @login
      .loginhint
        Log in to use grey sections

  -if section != Section::FMC
    %nav.leftbar
      -if section == Section::ALGS
        .leftitem.clickable= link_to 'Random Position', "/?pos=#{Position.random_name(@position_set)}&rnd=t"

      .leftitem
        =render 'find_by_alg'

      -if section == Section::ALGS
        .leftitem.clickable
          %label
            = check_box_tag(:zbll, 1, @position_set == 'eo')
            Lock EO (ZBLL)

      .leftitem
        %span.list-size
          = select_tag(:'list-size', options_for_select([['Small Text', 's'], ['Medium Text', 'm'], ['Large Text', 'l']], @text_size), class: 'list-size__select')

      - if (section == Section::ALGS || section == Section::ALGSETS)
        .leftitem
          %span.list-size
            =Fields::COMBOS.as_tag(@list_format, [], class: 'list-size__select', form: 'main-form')
          - unless @list_format.combos == 'none'
            %span.list-size.list-outline{style: "margin-top: 6px;"}
              =Fields::ALGSET.as_tag(@list_format, AlgSet.menu_options(@login), class: 'list-size__select', form: 'main-form')
          - else
            =Fields::ALGSET.as_hidden_field(@list_format)

      .leftitem.clickable#about-link About…

#about-box
  %p Birdflu aims to contain all knowledge of algorithms and positions for the last layer of Rubik's Cube, and present it in simple and useful ways. For now is has all algs up to 17 moves.
  %p
  %p Hand crafted by Lars Petrus in Oakland 2015-17.
  %p
    Big thanks to
    = link_to("Tom Rokicki", "http://tomas.rokicki.com/")
    for generating the algs!
  %hr
  %p To use the #{Section::FAVORITES} and #{Section::ALGSETS} sections, log in using a WCA account (top right). The #{Section::FMC} section is just a beginning.
  %hr
  %p Combo Alg Sets implement the old idea of solving LL in one look with only a few dozen memorized algs by using a pair of algs for each. ZBLL can be solved with only 14 algs, and the full LL with 39.
  %p
    Combo ready algs are marked by a
    %span.combo-ready c
  %hr
  %p "Birdflu" is the shortest English word containing the basic moves BRDFLU.
  %hr
  %p Questions: birdflu@lar5.com


:javascript
  var SECTION_PATHS = {"#{Section::ALGS}": '/', "#{Section::FAVORITES}": "#{galaxies_path}", "#{Section::ALGSETS}": "#{alg_sets_path}", "#{Section::FMC}": '/fmc?example=1'}
  $('#sectionator').change(function() {
    window.location.href = SECTION_PATHS[$(this).val()];
  });

  $('#zbll').on('click', function() {
    var addon = '';
    if ($(this).is(":checked")) {
      Cookies.set('zbll', 'Yep', { expires: 3650 });
      addon = '&poschange=eo-4'
    } else {
      Cookies.remove('zbll')
    }
    window.location = window.location.search + addon;
  });

  $('#list-size').on('change', function() {
    Cookies.set('size',$(this).val() , { expires: 3650 });
    window.location = window.location.search;
  });

  $(document).on('click', '#about-link', function(event) {
    $('#about-box').dialog({
      position: { my: 'center', at: 'top', of: 'body' },
      width: '305px',
      title: 'What is Birdflu?',
      modal: true,
      closeOnEscape: true,
      dialogClass: 'lars-dialog'
    });
  });

app/views/application/_page_rotation.html.haml
- update_url ||= false

.rotation-ui
  %h1
    %span rotate
  .buttons
    %a{class: 'show-pig', onclick: "rotate_page(-1);"} U'
    %a{class: 'show-pig', onclick: "rotate_page(1);"} U
    %a{class: 'show-pig', onclick: "rotate_page(2);"} U2
  .shortcuts
    shortcuts: , . /

:javascript
  $(document).on('keypress', function(event) {
    if (event.keyCode === 44) { rotate_page(-1); } // comma = 44
    if (event.keyCode === 46) { rotate_page(+1); } // period = 46
    if (event.keyCode === 47) { rotate_page(+2); } // slash = 47
  });

  var ALG_TEXT_SELECT = 'td.js-alg, td.js-combo span, .setupalg span';

  var U_TRANSPOSITIONS = {
     1: { R: 'F', F: 'L', L: 'B', B: 'R' },
     2: { R: 'L', F: 'B', L: 'R', B: 'F' },
     3: { R: 'B', F: 'R', L: 'F', B: 'L' },
  };
  function rotate_all_algs(rotation) {
    var diff = (rotation + 4) % 4;
    if (diff > 0) {
      var u_transposition = U_TRANSPOSITIONS[diff];
      $(ALG_TEXT_SELECT).text(function(i, current_text){
        result = '';
        for (var i = 0, len = current_text.length; i < len; i++) {
          result += u_transposition[current_text[i]] || current_text[i];
        }
        return result;
      });
    }
  }

  function spin_svgs(diff, progress) {
    $('svg g').attr("transform", "rotate(" + (page_rotation*90 + diff*90*progress) + ", 50, 50)");
  }

  function adjust_pos_name() {
    $('#headline_prot').text(['', '+U', '+U2', "+U'"][page_rotation]);
  }

  function adjust_url() {
    if (#{update_url}) {
      var old_url = window.location.search;
      var new_prot = 'prot=' + page_rotation;
      if (old_url.indexOf('prot') != -1) {
        history.replaceState('', '', old_url.replace(/prot=./, new_prot));
      } else {
        var sep = old_url.indexOf('?') == -1 ? '?' : '&';
        history.replaceState('', '', old_url + sep + new_prot);
      }
    }
  }

  function rotate_page(diff) {
    var algs_rotated = false;
    $('body').animate({ dummyAttr: '20px' },
      {
        duration:400,
        progress: function(animation, progress) {
          spin_svgs(diff, progress);

          var gray = Math.floor(400.0 * (0.5 - Math.abs(progress - 0.5)));
          $(ALG_TEXT_SELECT).attr("style", "color: rgb("+gray+","+gray+","+gray+");");

          if (progress > 0.5 && !algs_rotated) {
            rotate_all_algs(diff);
            algs_rotated = true;
          }
        },
        complete: function() {
          page_rotation = (page_rotation + diff + 4) % 4;
          adjust_url();
          adjust_pos_name();
          $(ALG_TEXT_SELECT).removeAttr("style"); // Remove grayness
        }
      }
    );
  }

  var page_rotation = #{@page_rotation || 0}; // Page wide state

  $(document).ready(function() {
    if (page_rotation > 0) {
      adjust_pos_name();
      spin_svgs(0, 0);
      rotate_all_algs(page_rotation);
    }
  });