config/routes.rb
Rails.application.routes.draw do

  get 'fmc/index'
  get 'status/index'

  get 'galaxies/remove_star'
  post 'galaxies/update_star'
  resources :galaxies , only: [:index, :show]

  match "/" => "positions#index", via: [:get, :post]
  get 'positions/:id', to: "positions#show"
  post 'positions/find_by_alg'

  get 'alg_sets/update_cookie/', to: "alg_sets#update_cookie"
  resources :alg_sets
  get 'alg_sets/compute/:ids', to: "alg_sets#compute"
  get 'alg_sets/:id/algs', to: "alg_sets#algs", as: "mirrored_list"

  get 'hemlig', to: 'status#index'
  get 'fmc', to: 'fmc#index'

  get "wca_callback" => "oauth#wca"
  get "wca_logout" => "oauth#wca_logout"
  get "fake_wca_login" => "oauth#fake_wca_login"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '*path', to: 'errors#not_found', via: :all

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Birdflu 1.0 β-ish
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-1030049-2', 'auto');
        ga('send', 'pageview');
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "flash_msgs"
    = yield

    .login{class: @dev_marker_class}
      - if @login
        #{@login.name}
        .logout
          = link_to 'Logout', wca_logout_path
      - else
        - if Rails.application.secrets.wca_oauth_client_secret
          %a{href: OauthController::WCA_LOGIN_URL}
            WCA Login
        - else
          = link_to 'Fake Login', fake_wca_login_path

    :javascript
      setTimeout("$('.flash_msgs').fadeOut(2000)", 5000)